### ISSUE TITLE
data loading/handling

### ISSUE THREAD

**Issue by johangithub** [tflearn/tflearn#157]
Hello, 

I'm very new to contributing to a library, using github and handling issues, so please call me out if I'm not carrying out this procedure properly. 

I noticed that when I ran examples, the data is loaded in that directory, instead of saving it in the /dataset directory.  For example, when I run alexnet in the example directory,
```Shell
((tf)) joehan@JoeMachine:~/tflearn/examples/images$ python -i alexnet.py
```
It creates a directory 17flowers in that directory. Wouldn't this trigger downloading files repeatedly for example files in different directory?

Another one I noticed is when I executed the command above was 
```Shell
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Starting to parse images...
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/home/joehan/anaconda3/envs/tf/lib/python3.5/site-packages/tflearn/data_utils.py in build_image_dataset_from_dir(directory, dataset_file, resize, convert_gray, filetypes, shuffle_data, categorical_Y)
    338     try:
--> 339         X, Y = pickle.load(open(dataset_file, 'rb'))
    340     except Exception:

FileNotFoundError: [Errno 2] No such file or directory: '17flowers/17flowers.pkl'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/home/joehan/tflearn/examples/images/alexnet.py in <module>()
     25 
     26 import tflearn.datasets.oxflower17 as oxflower17
---> 27 X, Y = oxflower17.load_data(one_hot=True)
     28 
     29 # Building 'AlexNet'

/home/joehan/anaconda3/envs/tf/lib/python3.5/site-packages/tflearn/datasets/oxflower17.py in load_data(dirname, resize_pics, shuffle, one_hot)
     32                                         convert_gray=False,
     33                                         shuffle_data=shuffle,
---> 34                                         categorical_Y=one_hot)
     35 
     36     return X, Y

/home/joehan/anaconda3/envs/tf/lib/python3.5/site-packages/tflearn/data_utils.py in build_image_dataset_from_dir(directory, dataset_file, resize, convert_gray, filetypes, shuffle_data, categorical_Y)
    339         X, Y = pickle.load(open(dataset_file, 'rb'))
    340     except Exception:
--> 341         X, Y = image_dirs_to_samples(directory, resize, convert_gray, filetypes)
    342         if categorical_Y:
    343             Y = to_categorical(Y, np.max(Y) + 1) # First class is '0'

/home/joehan/anaconda3/envs/tf/lib/python3.5/site-packages/tflearn/data_utils.py in image_dirs_to_samples(directory, resize, convert_gray, filetypes)
    318     if filetypes:
    319         if filetypes not in [list, tuple]: filetypes = list(filetypes)
--> 320     samples, targets = directory_to_samples(directory, flags=filetypes)
    321     for i, s in enumerate(samples):
    322         samples[i] = load_image(s)

/home/joehan/anaconda3/envs/tf/lib/python3.5/site-packages/tflearn/data_utils.py in directory_to_samples(directory, flags)
    472     targets = []
    473     label = 0
--> 474     classes = sorted(os.walk(directory).next()[1])
    475     for c in classes:
    476         c_dir = os.path.join(directory, c)

AttributeError: 'generator' object has no attribute 'next'
```

This was fixed by using \_\_next\_\_() instead of next() in data_utils.py
```python
     classes = sorted(os.walk(directory).__next__()[1])
     for c in classes:
         c_dir = os.path.join(directory, c)
         for sample in os.walk(c_dir).__next__()[2]:
             if not flags or any(flag in sample for flag in flags):
                 samples.append(os.path.join(c_dir, sample))
                 targets.append(label)
         label += 1
     return samples, targets
```

**Comment by aymericdamien** [comment]
The dataset is only downloaded if your workspace directory hasn't the dataset folder yet.
Yes, it may have issue between `next` in python2 and python3. We should fix that.

**Comment by stepseazy** [comment]
This is still not fixed on github

**Comment by handong1587** [comment]
I think this issue is still not fixed yet, I just come across this issue again on Windows 10 64 bit, Python 3.5. Have to manually change .next() to .__next__().
