### ISSUE TITLE
wrong cifar-10-batches path

### ISSUE THREAD

**Issue by migueldsw** [tflearn/tflearn#428]
Wrong path found when trying to load CIFAR-10 dataset through: 
`import tflearn.datasets.cifar10 as cifar10`
`X, Y = cifar10.load_data(one_hot=True)`

got:
`Traceback (most recent call last):
  File "loadcifar1.py", line 3, in <module>
    X, Y = cifar10.load_data(one_hot=True)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/datasets/cifar10.py", line 31, in load_data
    data, labels = load_batch(fpath)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/datasets/cifar10.py", line 57, in load_batch
    with open(fpath, 'rb') as f:
IOError: [Errno 2] No such file or directory: './cifar-10-batches-py/data_batch_1'`

**Comment by aymericdamien** [comment]
Can you update tflearn? I just fix it, it was some issues with newer versions of TensorFlow.

**Comment by migueldsw** [comment]
done! Now works fine. Thanks!

**Comment by Coderx7** [comment]
I am getting the same error. I have tensorflow 12.1 installed and then installed the stable version of tflearn (`pip install tflearn`) , then since I was getting different errors because of the updated tensorflow, I used this command to update to the latest version 
` pip install git+https://github.com/tflearn/tflearn.git`
and when I try to run a tflearn example, I get this error : 
`FileNotFoundError: [Errno 2] No such file or directory: 'cifar-10-batches-py/cifar-10-batches-py/data_batch_1'`

**Comment by ehfo0** [comment]
I did install the bleeding edge version of tflearn and still get the same error

**Comment by Anubhav-Bhargava** [comment]
Download the file again!
 
In your home folder a folder named "cifar-10-batches-py" would have been created. Delete that folder.
Run the command again and it will start downloading the dataset again.

Hope that helps :)

**Comment by ehfo0** [comment]
I did load cifar10 from keras and it worked
`from keras.datasets import cifar10`

**Comment by mzmmoazam** [comment]
## I had the same problem.
 
# So here is what you have to do.

if neural.py is my file using the CIFAR 10.

Arrange the files in this style
```
->  neural.py
->  cifar-10-batches-py
              ->  cifar-10-batches-py
                              ->  unzipped cifar-10 dataset
              ->  cifar-10-python.tar.gz

```

**Comment by joshuagithub** [comment]
Need Assistance
f = open('./data_set/'+folder_name+'/batches.meta', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './data_set/cifar_10/batches.meta'

Note: I am using updated tensorflow and update tflearn

After i install tflearn it download the files and it half way stops!

Any suggestion is always helpful

**Comment by joshuagithub** [comment]
How to use this line of code in coda (different respo to download cifar10 dataset)

wget -c https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz

**Comment by kingjr** [comment]
there's still an error the untar path is inconsistent with the load_data path

**Comment by daraamer** [comment]
Another alternative way is to download the dataset itself by using the link given in cs231n/datasets/get_datasets.sh
Once that is done, instead of using the lines:
 `wget http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz`
`tar -xzvf cifar-10-python.tar.gz`

Just use following line: 
`tar -xzvf <path where you put the data-set>cifar-10-python.tar.gz`

**Comment by BiserkaP** [comment]
> just use the command "rm -rf cifar-10-batches-py.tar.gz"and" rm -rf cifar-10-batches-py" to delete the tar.gz and the batches_py folder ,then it can run ,hope this can help you

It works
