### ISSUE TITLE
python 3 incompatible when use map function

### ISSUE THREAD

**Issue by HelloGithubTest** [tflearn/tflearn#559]
https://github.com/tflearn/tflearn/blob/master/tflearn/layers/core.py#L662
`    x = map(lambda t: tf.reshape(t, [-1, 1]+utils.get_incoming_shape(t)[1:]), x)
`
cause a compatible issue when using python3.  should change to
`x = list(map(lambda t: tf.reshape(t, [-1, 1]+utils.get_incoming_shape(t)[1:]), x))`

here is the exception I got:

...
  File "/anaconda/lib/python3.5/site-packages/tflearn/layers/core.py", line 654, in time_distributed
    return tf.concat(1, x)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1077, in concat
    return identity(values[0], name=scope)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1424, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
    raise err
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <map object at 0x159ca0630>

**Comment by aymericdamien** [comment]
Thanks for reporting that issue, I will send a fix.

**Comment by aymericdamien** [comment]
This should be working now

**Comment by HelloGithubTest** [comment]
the fix  at https://github.com/tflearn/tflearn/blob/master/tflearn/layers/core.py#L662
didn't solve the problem.
because in python3 map return a map object. it throw exception when execute tf.concat(1,x)

I'm still see exception when I use latest master code:

  File "/anaconda/lib/python3.5/site-packages/tflearn/layers/core.py", line 666, in time_distributed
    return tf.concat(1, x)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1077, in concat
    return identity(values[0], name=scope)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1424, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
    raise err
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/anaconda/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <map object at 0x12d326e80>

**Comment by Rithmax** [comment]
Hi,
Did you manage to fix this problem? I think its the same error in my case too. Error comes from, 
x = map(lambda t: tf.reshape(t, [-1, 1]+utils.get_incoming_shape(t)[1:]), x) . I updated both tensorflow and tflearn. But there is no effect. Can anyone please suggest me a solution for this? 

Error Message: 

File "LSTM_Train_many_to_many.py", line 121, in <module>
    net=network_initialization(no_classes,time_step)
  File "LSTM_Train_many_to_many.py", line 81, in network_initialization
    net = tflearn.time_distributed(lstm_net, tflearn.fully_connected,[14])    
  File "/usr/local/lib/python3.5/dist-packages/tflearn-0.2.2-py3.5.egg/tflearn/layers/core.py", line 663, in time_distributed
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1077, in concat
    return identity(values[0], name=scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1424, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
    raise err
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_util.py", line 441, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <map object at 0x7fd54afbd828>

**Comment by chrisplyn** [comment]
@Rithmax @HelloGithubTest 
I fixed the issue by changing following:
    try:
      x = map(lambda t: tf.reshape(t, [-1, 1]+utils.get_incoming_shape(t)[1:]), x)
    except:
      x = list(map(lambda t: tf.reshape(t, [-1, 1]+utils.get_incoming_shape(t)[1:]), x))
to
      x = list(map(lambda t: tf.reshape(t, [-1, 1]+utils.get_incoming_shape(t)[1:]), x))
      return tf.concat(x,1)
