### ISSUE TITLE
Error in tflearn.DNN()

### ISSUE THREAD

**Issue by Wermarter** [tflearn/tflearn#803]
[https://gist.github.com/Wermarter/9e0e29ee80adaa0f7af17b72d8e58a67](url)
I'm trying to code my own version of VAE based on your example [https://github.com/tflearn/tflearn/blob/master/examples/images/variational_autoencoder.py](url)
But my terminal said:

> Traceback (most recent call last):
  File "/home/wermarter/Desktop/ChienVAE.py", line 113, in <module>
    myVAE = VAE()
  File "/home/wermarter/Desktop/ChienVAE.py", line 28, in __init__
    self._build_graph()
  File "/home/wermarter/Desktop/ChienVAE.py", line 71, in _build_graph
    self.training_model = tflearn.DNN(training_net) # <========== Error
  File "/home/wermarter/anaconda3/lib/python3.5/site-packages/tflearn/models/dnn.py", line 64, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/home/wermarter/anaconda3/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 131, in __init__
    clip_gradients)
  File "/home/wermarter/anaconda3/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 651, in initialize_training_ops
    ema_num_updates=self.training_steps)
  File "/home/wermarter/anaconda3/lib/python3.5/site-packages/tflearn/summaries.py", line 239, in add_loss_summaries
    loss_averages_op = loss_averages.apply([loss] + other_losses)
  File "/home/wermarter/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/moving_averages.py", line 375, in apply
    colocate_with_primary=(var.op.type in ["Variable", "VariableV2"]))
  File "/home/wermarter/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/slot_creator.py", line 169, in create_zeros_slot
    else array_ops.shape(primary.initialized_value()))
AttributeError: 'Tensor' object has no attribute 'initialized_value'

**Comment by willduan** [comment]
`please try pip3 install git+ https://github.com/tflearn/tflearn.git`

**Comment by Wermarter** [comment]
Thank you, I've tried and got TFLearn update to 0.3.2 but the error is still here.
Btw, I ran some other examples with TFLearn and they all worked well. I believe there're some problem with my code (maybe TFLearn forgot to check something for me)

**Comment by Wermarter** [comment]
I figured out that this error only occurs on my TF 1.2.0. When running on TF 1.0.1 it showed up with another error:

> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1352, in zeros
>     output = constant(zero, shape=shape, dtype=dtype, name=name)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 99, in constant
>     tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 409, in make_tensor_proto
>     shape = [int(dim) for dim in shape]
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 409, in <listcomp>
>     shape = [int(dim) for dim in shape]
> TypeError: __int__ returned non-int (type NoneType)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Werma\Desktop\vae.py", line 107, in <module>
>     main()
>   File "C:\Users\Werma\Desktop\vae.py", line 101, in main
>     vae = VAE()
>   File "C:\Users\Werma\Desktop\vae.py", line 26, in __init__
>     self._build_graph()
>   File "C:\Users\Werma\Desktop\vae.py", line 67, in _build_graph
>     self.training_model = tflearn.Trainer(train_ops=trainop, tensorboard_dir=TENSORBOARD_DIR) # <====== Error
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py", line 131, in __init__
>     clip_gradients)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py", line 651, in initialize_training_ops
>     ema_num_updates=self.training_steps)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\summaries.py", line 239, in add_loss_summaries
>     loss_averages_op = loss_averages.apply([loss] + other_losses)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\moving_averages.py", line 375, in apply
>     colocate_with_primary=(var.op.type in ["Variable", "VariableV2"]))
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\slot_creator.py", line 121, in create_zeros_slot
>     val = array_ops.zeros(primary.get_shape().as_list(), dtype=dtype)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1354, in zeros
>     shape = ops.convert_to_tensor(shape, dtype=dtypes.int32, name="shape")
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 637, in convert_to_tensor
>     as_ref=False)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 702, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 128, in _tensor_shape_tensor_conversion_function
>     "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
> ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, 784)

**Comment by Wermarter** [comment]
Problem solved in https://stackoverflow.com/questions/44689522/attributeerror-tensor-object-has-no-attribute-initialized-value

**Comment by dengyueyun666** [comment]
@Wermarter Hello, I had the same problem, and I still don't know how to fix it. Can you give me some details? Thanks!

**Comment by Wermarter** [comment]
@dengyueyun666  Have you tried running your code with TF 1.0.1?
